import { CHANNEL_CREATE, CHANNEL_DELETE, CHANNEL_PINS_UPDATE, CHANNEL_RECIPIENT_ADD, CHANNEL_RECIPIENT_REMOVE, CHANNEL_UPDATE } from "./channels";
import { GUILD_APPLICATION_COMMAND_INDEX_UPDATE, GUILD_AUDIT_LOG_ENTRY_CREATE, GUILD_CREATE, GUILD_DELETE, GUILD_UPDATE } from "./guild";
import { STAGE_INSTANCE_CREATE, STAGE_INSTANCE_DELETE } from "./guild/stageinstance";
import {
	MESSAGE_ACK,
	MESSAGE_CREATE,
	MESSAGE_DELETE,
	MESSAGE_DELETE_BULK,
	MESSAGE_REACTION_ADD,
	MESSAGE_REACTION_REMOVE,
	MESSAGE_REACTION_REMOVE_ALL,
	MESSAGE_REACTION_REMOVE_EMOJI,
	MESSAGE_UPDATE,
} from "./message";
import { PRESENCE_UPDATE } from "./presence";
import { PASSIVE_UPDATE_V1, READY, READY_SUPPLEMENTAL, RESUMED, USER_SETTINGS_PROTO_UPDATE } from "./ready";
import connectedAccount from "./ready/connectedaccount";
import { SESSIONS_REPLACE } from "./ready/session";
import { RELATIONSHIP_ADD, RELATIONSHIP_REMOVE } from "./relationship";
import { TYPING_START } from "./typing";

import { Output } from "valibot";

export const dispatches = {
	CHANNEL_CREATE,
	CHANNEL_DELETE,
	CHANNEL_PINS_UPDATE,
	CHANNEL_RECIPIENT_ADD,
	CHANNEL_RECIPIENT_REMOVE,
	CHANNEL_UPDATE,
	GUILD_APPLICATION_COMMAND_INDEX_UPDATE,
	GUILD_AUDIT_LOG_ENTRY_CREATE,
	GUILD_CREATE,
	GUILD_DELETE,
	GUILD_UPDATE,
	MESSAGE_ACK,
	MESSAGE_CREATE,
	MESSAGE_DELETE,
	MESSAGE_DELETE_BULK,
	MESSAGE_REACTION_ADD,
	MESSAGE_REACTION_REMOVE,
	MESSAGE_REACTION_REMOVE_ALL,
	MESSAGE_REACTION_REMOVE_EMOJI,
	MESSAGE_UPDATE,
	PASSIVE_UPDATE_V1,
	PRESENCE_UPDATE,
	READY,
	READY_SUPPLEMENTAL,
	RELATIONSHIP_ADD,
	RELATIONSHIP_REMOVE,
	RESUMED,
	SESSIONS_REPLACE,
	STAGE_INSTANCE_CREATE: STAGE_INSTANCE_CREATE,
	STAGE_INSTANCE_DELETE: STAGE_INSTANCE_DELETE,
	TYPING_START,
	USER_CONNECTIONS_UPDATE: connectedAccount,
	USER_SETTINGS_PROTO_UPDATE,
};

export type _dispatches = {
	[key in keyof typeof dispatches]: Output<(typeof dispatches)[key]>;
};
