import { InferOutput } from "valibot";

import { CHANNEL_CREATE, CHANNEL_DELETE, CHANNEL_PINS_UPDATE, CHANNEL_RECIPIENT_ADD, CHANNEL_RECIPIENT_REMOVE, CHANNEL_UPDATE } from "./channels";
import {
	GUILD_APPLICATION_COMMAND_INDEX_UPDATE,
	GUILD_AUDIT_LOG_ENTRY_CREATE,
	GUILD_BAN_ADD,
	GUILD_CREATE,
	GUILD_DELETE,
	GUILD_SCHEDULED_EVENT_USER_ADD,
	GUILD_SCHEDULED_EVENT_USER_REMOVE,
	GUILD_UPDATE,
} from "./guild";
import { GUILD_JOIN_REQUEST_CREATE, GUILD_JOIN_REQUEST_DELETE, GUILD_JOIN_REQUEST_UPDATE } from "./guild/joinrequest";
import { GUILD_MEMBER_ADD, GUILD_MEMBER_REMOVE, GUILD_MEMBER_UPDATE, GUILD_MEMBERS_CHUNK } from "./guild/member";
import { GUILD_ROLE_CREATE, GUILD_ROLE_DELETE, GUILD_ROLE_UPDATE } from "./guild/role";
import { GUILD_SOUNDBOARD_SOUND_CREATE, GUILD_SOUNDBOARD_SOUND_DELETE, GUILD_SOUNDBOARD_SOUND_UPDATE } from "./guild/soundboard";
import { STAGE_INSTANCE_CREATE, STAGE_INSTANCE_DELETE } from "./guild/stageinstance";
import { CALL_CREATE, CALL_DELETE, VOICE_CHANNEL_STATUS_UPDATE, VOICE_STATE_UPDATE } from "./guild/voicestate";
import {
	MESSAGE_CREATE,
	MESSAGE_DELETE,
	MESSAGE_DELETE_BULK,
	MESSAGE_REACTION_ADD,
	MESSAGE_REACTION_ADD_MANY,
	MESSAGE_REACTION_REMOVE,
	MESSAGE_REACTION_REMOVE_ALL,
	MESSAGE_REACTION_REMOVE_EMOJI,
	MESSAGE_UPDATE,
} from "./message";
import { PRESENCE_UPDATE } from "./presence";
import { CHANNEL_PINS_ACK, GUILD_FEATURE_ACK, MESSAGE_ACK, RECENT_MENTION_DELETE, USER_NON_CHANNEL_ACK } from "./readstate";
import { PASSIVE_UPDATE_V1, PASSIVE_UPDATE_V2, READY, READY_SUPPLEMENTAL, RESUMED, USER_UPDATE } from "./ready";
import connectedAccount from "./ready/connectedaccount";
import { SESSIONS_REPLACE } from "./ready/session";
import { RELATIONSHIP_ADD, RELATIONSHIP_REMOVE } from "./relationship";
import { USER_GUILD_SETTINGS_UPDATE, USER_SETTINGS_PROTO_UPDATE } from "./settings";
import { CONVERSATION_SUMMARY_UPDATE } from "./summary";
import { THREAD_CREATE, THREAD_DELETE, THREAD_LIST_SYNC, THREAD_MEMBER_UPDATE, THREAD_MEMBERS_UPDATE, THREAD_UPDATE } from "./thread";
import { TYPING_START } from "./typing";

export const dispatches = {
	CALL_CREATE,
	CALL_DELETE,
	CHANNEL_CREATE,
	CHANNEL_DELETE,
	CHANNEL_PINS_ACK,
	CHANNEL_PINS_UPDATE,
	CHANNEL_RECIPIENT_ADD,
	CHANNEL_RECIPIENT_REMOVE,
	CHANNEL_UPDATE,
	CONVERSATION_SUMMARY_UPDATE,
	GUILD_APPLICATION_COMMAND_INDEX_UPDATE,
	GUILD_AUDIT_LOG_ENTRY_CREATE,
	GUILD_BAN_ADD,
	GUILD_CREATE,
	GUILD_DELETE,
	GUILD_FEATURE_ACK,
	GUILD_JOIN_REQUEST_CREATE,
	GUILD_JOIN_REQUEST_DELETE,
	GUILD_JOIN_REQUEST_UPDATE,
	GUILD_MEMBER_ADD,
	GUILD_MEMBER_REMOVE,
	GUILD_MEMBER_UPDATE,
	GUILD_MEMBERS_CHUNK,
	GUILD_ROLE_CREATE,
	GUILD_ROLE_DELETE,
	GUILD_ROLE_UPDATE,
	GUILD_SCHEDULED_EVENT_USER_ADD,
	GUILD_SCHEDULED_EVENT_USER_REMOVE,
	GUILD_SOUNDBOARD_SOUND_CREATE,
	GUILD_SOUNDBOARD_SOUND_DELETE,
	GUILD_SOUNDBOARD_SOUND_UPDATE,
	GUILD_UPDATE,
	MESSAGE_ACK,
	MESSAGE_CREATE,
	MESSAGE_DELETE,
	MESSAGE_DELETE_BULK,
	MESSAGE_REACTION_ADD,
	MESSAGE_REACTION_ADD_MANY,
	MESSAGE_REACTION_REMOVE,
	MESSAGE_REACTION_REMOVE_ALL,
	MESSAGE_REACTION_REMOVE_EMOJI,
	MESSAGE_UPDATE,
	PASSIVE_UPDATE_V1,
	PASSIVE_UPDATE_V2,
	PRESENCE_UPDATE,
	READY,
	READY_SUPPLEMENTAL,
	RECENT_MENTION_DELETE,
	RELATIONSHIP_ADD,
	RELATIONSHIP_REMOVE,
	RESUMED,
	SESSIONS_REPLACE,
	STAGE_INSTANCE_CREATE,
	STAGE_INSTANCE_DELETE,
	THREAD_CREATE,
	THREAD_DELETE,
	THREAD_LIST_SYNC,
	THREAD_MEMBER_UPDATE,
	THREAD_MEMBERS_UPDATE,
	THREAD_UPDATE,
	TYPING_START,
	USER_CONNECTIONS_UPDATE: connectedAccount,
	USER_GUILD_SETTINGS_UPDATE,
	USER_NON_CHANNEL_ACK,
	USER_SETTINGS_PROTO_UPDATE,
	USER_UPDATE,
	VOICE_CHANNEL_STATUS_UPDATE,
	VOICE_STATE_UPDATE,
};

export type _dispatches = {
	[key in keyof typeof dispatches]: InferOutput<(typeof dispatches)[key]>;
};
